apiVersion: v1
kind: Service
metadata:
  name: kukuk-backend-service
  namespace: enes-prod
spec:
  selector:
    app: kukuk-backend
  ports:
    - protocol: TCP
      port: 80                # Interner Cluster-Port
      targetPort: 8080        # Weiterleitung auf Container-Port
  type: ClusterIP             # Interner Zugriff 
