apiVersion: v1
kind: Service
metadata:
  name: kukuk-frontend-service
  namespace: enes-prod
spec:
  selector:
    app: kukuk-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
