apiVersion: v1
kind: Service
metadata:
  name: kukuk-backend-service
  namespace: enes-dev
spec:
  selector:
    app: kukuk-backend      
  ports:
    - protocol: TCP
      port: 80              # Service-Port im Cluster
      targetPort: 8081      # Weiterleitung an Port im Container
  type: ClusterIP           # Interner Cluster-Service 
